package com.dragonaltar.animation;
public enum AnimationActionType {
	SOUND, PARTICLE, PARTICLE_RING, PARTICLE_SPIRAL, TITLE, SUBTITLE, ACTION_BAR, BOSS_BAR, LIGHTNING_EFFECT, DISPLAY_MOVE, DISPLAY_SCALE, DISPLAY_ROTATE, DISPLAY_FADE, PLAYER_GLOW, PLAYER_LEVITATE, TEMPORARY_WINGS, BROADCAST, WAIT
}
